blank_issues_enabled: false
contact_links:
  - name: "Check if existing issues already exist"
    url: https://github.com/zSemper/fluid_control/issues
  - name: "Fluid Control's forum page"
    url: https://mcreator.net/plugin/116558/fluid-control
    about: Alternative place to report bugs or feature requests, also place for support questions